// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: response.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.korilin.pintask.protocol;

@kotlin.jvm.JvmName("-initializeresponseBody")
public inline fun responseBody(block: com.korilin.pintask.protocol.ResponseBodyKt.Dsl.() -> kotlin.Unit): com.korilin.pintask.protocol.Response.ResponseBody =
  com.korilin.pintask.protocol.ResponseBodyKt.Dsl._create(com.korilin.pintask.protocol.Response.ResponseBody.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.korilin.pintask.protocol.ResponseBody`
 */
public object ResponseBodyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.korilin.pintask.protocol.Response.ResponseBody.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.korilin.pintask.protocol.Response.ResponseBody.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.korilin.pintask.protocol.Response.ResponseBody = _builder.build()

    /**
     * `int32 code = 1;`
     */
    public var code: kotlin.Int
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * `int32 code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * `string msg = 2;`
     */
    public var msg: kotlin.String
      @JvmName("getMsg")
      get() = _builder.getMsg()
      @JvmName("setMsg")
      set(value) {
        _builder.setMsg(value)
      }
    /**
     * `string msg = 2;`
     */
    public fun clearMsg() {
      _builder.clearMsg()
    }

    /**
     * `bytes data = 3;`
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * `bytes data = 3;`
     */
    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.korilin.pintask.protocol.Response.ResponseBody.copy(block: com.korilin.pintask.protocol.ResponseBodyKt.Dsl.() -> kotlin.Unit): com.korilin.pintask.protocol.Response.ResponseBody =
  com.korilin.pintask.protocol.ResponseBodyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

