// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: response.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.korilin.pintask.protocol;

